### ISSUE TITLE
Dev help

### ISSUE THREAD

**Issue by positlabs** [makenai/node-uvc-control#11]
@makenai, would you like my help in developing this lib? It hasn't been very active since last year, and I'd like to rectify that :)

I'm hoping to write a cross-platform webcam controller app, using Electron.

**Comment by makenai** [comment]
Sure! Sorry to say that I'm not working on it actively at the moment. I'd welcome pull requests or a fork if you prefer. At the moment it does everything I needed for my project!

**Comment by positlabs** [comment]
Awesome! I'll start working on it. I have 4 webcams to test with, currently. Logitech Brio, c920, c930, and a Microsoft Lifecam.

Offhand, do you know how we could apply settings to built-in webcams? Understandably, mine isn't showing in the list of usb devices.

**Comment by makenai** [comment]
I could be remembering wrong, but I think mine was showing up on the mac? I remember I ended up having to do a few backflips to install USB Prober, which used to be included in XCode but is not currently. Maybe that's where I saw it if it didn't show up in list-devices.js?

https://embswit.wordpress.com/2014/12/08/usb-prober-in-os-x-mavericks/

**Comment by makenai** [comment]
OK, don't go down that path. I just double checked and it does not show up on USB Prober either.

**Comment by makenai** [comment]
OK, for what it's worth, you can see the vendor and device id's in system profiler or by running the command `system_profiler -detailLevel full` from the commandline. Mine lists the following: `Apple Camera VendorID_0x106B ProductID_0x1570`. Not sure it's really a usb device though. :/

**Comment by positlabs** [comment]
Huh, ok. I'll make a ticket for it

**Comment by positlabs** [comment]
@makenai I'd be happy to become a collaborator if you'll have me

**Comment by makenai** [comment]
@positlabs You've got it! Thanks for offering.

**Comment by positlabs** [comment]
Awesome!
