### ISSUE TITLE
how to caputure photo or video?

### ISSUE THREAD

**Issue by lhr000lhr** [makenai/node-uvc-control#17]
how to caputure photo or video?

**Comment by positlabs** [comment]
This lib is just for setting controls on UVC devices. 

You can do this with web apis like these: 

https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
https://developer.mozilla.org/en-US/docs/Web/API/MediaStream_Recording_API

**Comment by positlabs** [comment]
You could also use ffmpeg. https://trac.ffmpeg.org/wiki/Capture/Webcam

**Comment by lhr000lhr** [comment]
i see. but I want to capture fill resolution pic,rather than a frame in video. can you help me?

**Comment by positlabs** [comment]
You can use a dslr that is compatible with gphoto2 if you want to take still photos.

http://gphoto.org/proj/gphoto2/
