### ISSUE TITLE
absolutePanTilt

### ISSUE THREAD

**Issue by mattapperson** [makenai/node-uvc-control#4]
I see the example in the read-me, and I have the same camera as you... but can't seem to get that one control to have any effect (using Photo Booth the verify). Things like saturation work just fine though... any chance you might be able to help?

**Comment by mattapperson** [comment]
To answer anyone else questions here... it does work, setting the values is just hard to sort out due to getRaw not being an implemented method... I added support for it in my fork and created a PR

**Comment by positlabs** [comment]
PR was merged. Thanks!
