### ISSUE TITLE
LIBUSB_ERROR_NOT_SUPPORTED on windows 10

### ISSUE THREAD

**Issue by bschmitlin** [makenai/node-uvc-control#5]
Repro steps on Windows 10 64bit:
- in new folder run: npm install uvc-control (which runs fine, including node-gyp compile steps) 
- node node_modules/list-devices.js

result: Error: LIBUSB_ERROR_NOT_SUPPORTED

are there any extra dependencies to install or is windows not supported? Since you mention the device manager I assumed that it was.

Thanks!

**Comment by mattapperson** [comment]
@bschmitlin this lib uses node-usb and node-usb requires a WinUSB driver be installed on widows

**Comment by bschmitlin** [comment]
thank you @mattapperson, I'll give it a try. Could we add that information to the readme? Just a sentence or 2 in the "installation" section would go a long way to avoid confusion for others.

**Comment by positlabs** [comment]
Ideally we would install the dependencies when the user runs `npm install`.

We can make a preinstall script that will install deps based on OS.
https://docs.npmjs.com/misc/scripts

**Comment by positlabs** [comment]
Nevermind... I think dependency installation should be handled by the `usb` module, and not `node-uvc-control`. 

I do agree about documenting it, though. I'm going to add this snippet to the readme. Taken from [usb](https://www.npmjs.com/package/usb)

> Use [Zadig](https://sourceforge.net/projects/libwdi/files/zadig/) to install the WinUSB driver.

**Comment by positlabs** [comment]
OK, it's been documented. https://github.com/makenai/node-uvc-control/commit/bc8bb83796e4b55434a389cd2e220aee47425e04

**Comment by nospam2k** [comment]
Sorry to reopen this but is there a way to confirm the WinUSB is installed correctly. I actually compiled Zadig from libwdi so I was sure to use x64 (I didn't know if that would make a difference on the install of the driver itself but to be safe), ran Zadig and followed these directions I found elseware:

```
Connect your camera
Start Zadig
In Zadig under ‘Options’ check the ‘List All Devices’ option
In the drop down box select your camera
Select the WinUSB driver
Press the ‘Replace Driver’ button to install the WinUSB driver
```

On my camera there are two USB device drivers hidusb and usbvideo so I replaced usbvideo with WinUSB and now in the device manager I see in driver file details winusb.sys.

I cloned the repo and just did npm install.

When I run test/discover.js I get LIBUSB_ERROR_NOT_SUPPORTED.

This is Windows 10 x64

**Comment by Chris2011** [comment]
I had the same problem, with the LIBUSB_ERROR_NOT_SUPPORTED. After googling I find the solution.
* Open Zadig
* Go to options -> List all devices
* Select the usb flash drive in the DropDownListBox
* See the driver, which is installed for that device

For me it was a different one and I've overwritten it with WinUSB. After this, I don't get the error anymore, just undefined, but this could be from my code. Maybe didn't open the connection to the device, dunno. But maybe it helps someone.
